version: '3'

services:
    rif-relay:
        container_name: rif-relay-server
        build:
            context: .
        ports:
            - '8090:8090'
        volumes:
            - './environment:/srv/app/environment'
