version: '3'

services:
    rif-relay:
        container_name: rif-relay-server
        build:
            context: .
        entrypoint: sh -c 'node dist/commands/Start.js --config server-config.json'
        ports:
            - '8090:8090'
        volumes:
            - './environment:/srv/app/environment'
