version: '3'

services:
    rif-relay:
        build:
            context: .
        entrypoint: 'node dist/commands/Start.js --config server-config.rwm.json'
        ports:
            - '8090:8090'
        volumes:
            - './environment:/srv/app/environment'
