version: '3'

services:
    rif-relay:
        build:
            context: .
        environment:
            - NODE_ENV=$NODE_ENV
        ports:
            - '8090:8090'
        volumes:
            - './environment:/srv/app/environment' # this folder should be specifed in config.app.workdir
