version: '3'

services:
    rif-relay:
        build:
            context: .
        entrypoint: '$NODE_ENV npm run start'
        ports:
            - '8090:8090'
        volumes:
            - './environment:/srv/app/environment'
