---
name: CD for QA

on:
    push:
        branches: [main]

jobs:
    deploy-qa:
        runs-on: ubuntu-latest
        environment:
            name: QA

        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: ${{ secrets.QA_ROLE_ARN }}
                  aws-region: ${{ secrets.QA_AWS_REGION }}

            - name: Deploy rif-relay-server on QA
              run: |
                  aws ssm send-command \
                      --document-name "AWS-RunRemoteScript" \
                      --instance-ids "${{ secrets.QA_EC2_ID }}" \
                      --region=${{ secrets.QA_AWS_REGION }} \
                      --parameters '{"sourceType":["GitHub"],"sourceInfo":["{\"owner\":\"rootstock\", \"repository\":\"ask-devops\", \"path\": \"rif-relay/\", \"tokenInfo\":\"{{ssm-secure:github-token}}\"}"],"commandLine":["deploy-qa.sh"]}'
