---
name: CD for RIF-Wallet-Testnet

on:
    push:
        tags:
            - '**beta-rifwallet**'

jobs:
    deploy-rif-wallet-testnet:
        runs-on: ubuntu-latest
        environment:
            name: RIF-Wallet-Testnet

        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: ${{ secrets.RWT_ROLE_ARN }}
                  aws-region: ${{ secrets.RWT_AWS_REGION }}

            - name: Deploy rif-relay-server on RWT
              run: |
                  aws ssm send-command \
                      --document-name "AWS-RunRemoteScript" \
                      --instance-ids ""${{ secrets.RWT_EC2_ID }}"" \
                      --region=${{ secrets.RWT_AWS_REGION }} \
                      --parameters '{"sourceType":["GitHub"],"sourceInfo":["{\"owner\":\"rootstock\", \"repository\":\"ask-devops\", \"path\": \"rif-relay/\", \"tokenInfo\":\"{{ssm-secure:github-token}}\"}"],"commandLine":["deploy-rwt.sh"]}'
